### ISSUE TITLE
Get Holidays from Google API

### ISSUE THREAD

**Issue by amman98** [amman98/Random-Word-Calendar#4]
## User Story
As a user, I want to be notified of a holiday so that I can better organize my day

## Acceptance Criteria
- [x] Use this API: [Google Calendar API](https://developers.google.com/calendar/api/v3/reference/events/list?apix=true#try-it)
- [x] Retrieve holidays and their given date

**Comment by TanyaSilyutina** [comment]
Added the functionality for the API to retrieve the holiday and the date. They're console logged per function call. The console displays an array of objects; the object's key:value pair is holiday:date
