### ISSUE TITLE
Desktop view | Random word display

### ISSUE THREAD

**Issue by amman98** [amman98/Random-Word-Calendar#5]
## User Story
As a user, I want to be shown a new word every day so that I can expand my vocabulary

## Acceptance Criteria
- [x] Reference the following API: [Words API](https://www.wordsapi.com/docs/)
- [x] When I click the random word button, the API retrieves a random word in desktop view
- [x] Display if the word is a noun, verb, etc.

**Comment by TanyaSilyutina** [comment]
Added the functionality for the API to retrieve the random word and the definition. They're console logged per function call.
