### ISSUE TITLE
Create URL's for querying API's

### ISSUE THREAD

**Issue by amman98** [amman98/Random-Word-Calendar#7]
## User Story
As a developer, I want to have a list of resources to reference when I write code so that I can quickly access API information

## Acceptance Criteria
- [x] URL contains parameters that provides response in JSON format
- [x] Response contains data that can be used to display necessary content on landing page
- [x] Pulls data from [Google API](https://developers.google.com/calendar/api/v3/reference/events/list#try-it)
- [x] Pulls data from [Words API](https://www.wordsapi.com/docs/)

**Comment by TanyaSilyutina** [comment]
This is completed. All the requirements have been satisfied in my API commit.
